name: Playwright Tests (WebDriver, macOS)
on:
  workflow_dispatch

jobs:
  test:
    timeout-minutes: 10
    # macOS 12 for now, please refer to GH Actions docs
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run Safari test with Playwright
      run: npx playwright test --project="Safari Webdriver" webdriver.spec.ts
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 2
